---
apiVersion: v1
kind: Service
metadata:
  name: event-streamer-nodeport
  namespace: event-streamer
  labels:
    app.kubernetes.io/name: event-streamer
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: event-streamer
  ports:
    - name: http2-server
      port: 50051
      targetPort: http2-server
      nodePort: 30009
    - name: grpc-server
      port: 50052
      targetPort: grpc-server
      nodePort: 30010
